apiVersion: v1
kind: Service
metadata:
  name: {{ include "slice-api.fullname" . }}
  labels:
    {{- include "slice-api.labels" . | nindent 4 }}
  annotations:
    {{- range $k, $v := .Values.service.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "slice-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
