# config.yaml
# Example configuration file for intent-mcp

mcp_server:
  host: "mcp-server.smo"
  port: 8000

mcp_client:
  host: "127.0.0.1"
  port: 9200

rapp:
  host: "rapp.ricrapp.svc.cluster.local"
  port: 8090

llm: openai
