# config.yaml

PlmnId:
  mcc: "208"
  mnc: "93"

nonrtric:
  base_url_pms: "http://nonrtricgateway.nonrtric.svc.cluster.local:9090/a1-policy/v2/policies"
  service_id: "intentSlice"
  ric_id: "ric4"
  policytype_id: 10002

rapp:
  host: "127.0.0.1"
  port: 8090
