{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  config.yaml: |-
    mcp_client:
      host: {{ .Values.config.host | quote }}
      port: {{ .Values.config.port }}
{{- end }}
