# Default values for rApp Helm chart.
# Override these with --set or a custom values file.

image:
  repository: docker.io/gabrielasmachado/rapp
  tag: "2642c98-dirty"
  pullPolicy: Always
  # pullSecrets: [] # e.g. - name: myregistrysecret

service:
  type: ClusterIP
  port: 8090
  annotations: {}

resources: {}
#  limits:
#    cpu: 200m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

env: {}
#  EXAMPLE_VAR: some-value

config:
  enabled: true
  PlmnId:
    mcc: "208"
    mnc: "93"
  nonrtric:
    base_url_pms: "http://nonrtricgateway.nonrtric.svc.cluster.local:9090/a1-policy/v2/policies"
    service_id: "intentSlice"
    ric_id: "ric4"
    policytype_id: 10002
  rapp:
    host: "0.0.0.0"
    port: 8090

labels: {}

podAnnotations: {}

replicaCount: 1

probes:
  enabled: false
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

nodeSelector: {}
tolerations: []
affinity: {}
