# Default values for frontend Helm chart.
# Override these with --set or a custom values file.

image:
  repository: docker.io/gabrielasmachado/frontend
  tag: "d54a989-dirty"
  pullPolicy: Always
  # pullSecrets: [] # e.g. - name: myregistrysecret

service:
  type: ClusterIP
  port: 8501
  annotations: {}

resources: {}
#  limits:
#    cpu: 200m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

env: {}

config:
  enabled: true
  host: "mcp-client.smo.svc.cluster.local"
  port: 9100

labels: {}

podAnnotations: {}

replicaCount: 1

probes:
  enabled: false
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

nodeSelector: {}
tolerations: []
affinity: {}
